/*
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
 */
package ru.VladG24YT.ConsoleSCP;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * Вот эту фигню не трогать! Она работает
 *
 * @author NetBeans IDE
 */
public class GUIMaker extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public GUIMaker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        userPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameView = new javax.swing.JTextField();
        accessLabel = new javax.swing.JLabel();
        accessView = new javax.swing.JTextField();
        msgButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        mainNavigationPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dirArea = new javax.swing.JTextArea();
        subNavigationPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileArea = new javax.swing.JTextArea();
        outputPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();
        loggerPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        loggerArea = new javax.swing.JTextArea();
        controlPanel = new javax.swing.JPanel();
        pathField = new javax.swing.JTextField();
        commandInputField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SCP Console test");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        mainPanel.setName(""); // NOI18N
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        userPanel.setBackground(new java.awt.Color(0, 0, 0));
        userPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        usernameLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Имя пользователя:");

        usernameView.setBackground(new java.awt.Color(0, 0, 0));
        usernameView.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        usernameView.setForeground(new java.awt.Color(255, 255, 255));
        usernameView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameViewActionPerformed(evt);
            }
        });

        accessLabel.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        accessLabel.setForeground(new java.awt.Color(255, 255, 255));
        accessLabel.setText("Уровень доступа:");

        accessView.setBackground(new java.awt.Color(0, 0, 0));
        accessView.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        accessView.setForeground(new java.awt.Color(255, 255, 255));
        accessView.setText("Класс C");

        msgButton.setBackground(new java.awt.Color(0, 0, 0));
        msgButton.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        msgButton.setForeground(new java.awt.Color(255, 255, 255));
        msgButton.setText("📧");
        msgButton.setActionCommand("msg");
        msgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(0, 0, 0));
        helpButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        helpButton.setForeground(new java.awt.Color(255, 255, 255));
        helpButton.setText("!");
        helpButton.setActionCommand("help");
        helpButton.setAlignmentY(0.0F);
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(accessLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameView)
                    .addComponent(accessView, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(msgButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(msgButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accessView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accessLabel)
                    .addComponent(helpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(37, 37, 37))
        );

        mainNavigationPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainNavigationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        dirArea.setBackground(new java.awt.Color(0, 0, 0));
        dirArea.setColumns(20);
        dirArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        dirArea.setForeground(new java.awt.Color(255, 255, 255));
        dirArea.setRows(5);
        dirArea.setText("Protocols\nReports\nAdditional Documents\n");
        dirArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        dirArea.setEnabled(false);
        jScrollPane1.setViewportView(dirArea);

        javax.swing.GroupLayout mainNavigationPanelLayout = new javax.swing.GroupLayout(mainNavigationPanel);
        mainNavigationPanel.setLayout(mainNavigationPanelLayout);
        mainNavigationPanelLayout.setHorizontalGroup(
            mainNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainNavigationPanelLayout.setVerticalGroup(
            mainNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        subNavigationPanel.setBackground(new java.awt.Color(0, 0, 0));
        subNavigationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        fileArea.setBackground(new java.awt.Color(0, 0, 0));
        fileArea.setColumns(20);
        fileArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        fileArea.setForeground(new java.awt.Color(255, 255, 255));
        fileArea.setRows(5);
        fileArea.setText("FILE\nFILE\nFILE\nEXE");
        fileArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fileArea.setEnabled(false);
        jScrollPane2.setViewportView(fileArea);

        javax.swing.GroupLayout subNavigationPanelLayout = new javax.swing.GroupLayout(subNavigationPanel);
        subNavigationPanel.setLayout(subNavigationPanelLayout);
        subNavigationPanelLayout.setHorizontalGroup(
            subNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        subNavigationPanelLayout.setVerticalGroup(
            subNavigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subNavigationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        outputPanel.setBackground(new java.awt.Color(0, 0, 0));
        outputPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        outputPanel.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N

        outputArea.setBackground(new java.awt.Color(0, 0, 0));
        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        outputArea.setForeground(new java.awt.Color(255, 255, 255));
        outputArea.setRows(5);
        outputArea.setText("С возвращением, "+usernameView.getText()+"!\nТекущая дата: "+new SimpleDateFormat("E dd.MM.yyyy").format(new Date()) + "\n------------------------------");
        outputArea.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        outputArea.setEnabled(false);
        jScrollPane3.setViewportView(outputArea);

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );

        loggerPanel.setBackground(new java.awt.Color(0, 0, 0));
        loggerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        loggerArea.setBackground(new java.awt.Color(0, 0, 0));
        loggerArea.setColumns(20);
        loggerArea.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        loggerArea.setForeground(new java.awt.Color(0, 255, 0));
        loggerArea.setRows(5);
        loggerArea.setText("User@active");
        loggerArea.setDisabledTextColor(new java.awt.Color(102, 255, 102));
        loggerArea.setEnabled(false);
        jScrollPane4.setViewportView(loggerArea);

        javax.swing.GroupLayout loggerPanelLayout = new javax.swing.GroupLayout(loggerPanel);
        loggerPanel.setLayout(loggerPanelLayout);
        loggerPanelLayout.setHorizontalGroup(
            loggerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loggerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        loggerPanelLayout.setVerticalGroup(
            loggerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loggerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );

        controlPanel.setBackground(new java.awt.Color(0, 0, 0));
        controlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        pathField.setBackground(new java.awt.Color(0, 0, 0));
        pathField.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        pathField.setForeground(new java.awt.Color(255, 255, 255));
        pathField.setText("C:/Users/Default/Desktop/");
        pathField.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        pathField.setEnabled(false);

        commandInputField.setBackground(new java.awt.Color(0, 0, 0));
        commandInputField.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        commandInputField.setForeground(new java.awt.Color(255, 255, 255));
        commandInputField.setToolTipText("Поле ввода команд");

        enterButton.setBackground(new java.awt.Color(0, 0, 0));
        enterButton.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        enterButton.setForeground(new java.awt.Color(255, 255, 255));
        enterButton.setText("Ввод");
        enterButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 3));
        enterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pathField)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(commandInputField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(commandInputField)
                    .addComponent(enterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scp_logo.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scp.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel2.setMinimumSize(new java.awt.Dimension(10, 10));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(mainNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(subNavigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(userPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loggerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(219, 219, 219))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loggerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subNavigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        JOptionPane.showConfirmDialog(mainPanel, "Добро пожаловать в SCP Console v0.0.1 Java Edition\n\nЧто нового:\n- Доделан интерфейс\n- Добавлено обучение по обращению с интерфейсом", "Приветствие", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 603, Short.MAX_VALUE)
        );

        mainPanel.getAccessibleContext().setAccessibleName("");
        usernameView.setText(JOptionPane.showInputDialog(mainPanel, "Введите имя пользователя: ", "Вход", JOptionPane.QUESTION_MESSAGE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameViewActionPerformed

    private void msg(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg
        if (evt.getActionCommand().equals("msg")) {
            JOptionPane.showMessageDialog(mainPanel, "ОТ: Администратор\nКОМУ: " + usernameView.getText() + "\n\nПоздравляем с приёмом на работу в класс C. Воспользуётесь командой \'tutorial\', чтобы ознакомиться с интерфейсом вашего нового рабочего места и ожидайте дальнейших инструкций", "ПИСЬМО ОТ administrator@scpfoundation.org", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_msg

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
        if (evt.getActionCommand().equals("help")) {
            JOptionPane.showMessageDialog(mainPanel, "Список доступных команд:\n\nexit - завершить сеанс\nhelp - вывод этого окна\ntutorial - просмотреть обучение заново", "Справка по командам", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_helpButtonActionPerformed

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterButtonActionPerformed
        if (evt.getActionCommand().equals("enter")) {
            String command = commandInputField.getText();
            commandInputField.setText("");
            if (command.equals("tutorial")) {
                //1st Stage
            }
        }
    }//GEN-LAST:event_enterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMaker().setVisible(true);
            }
        });

        Timer ticks = new Timer(60, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                loggerArea.setText(loggerArea.getText() + "\nUser@active");
            }
        });
        ticks.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accessLabel;
    private static javax.swing.JTextField accessView;
    private static javax.swing.JTextField commandInputField;
    private javax.swing.JPanel controlPanel;
    private static javax.swing.JTextArea dirArea;
    private static javax.swing.JButton enterButton;
    private static javax.swing.JTextArea fileArea;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private static javax.swing.JTextArea loggerArea;
    private javax.swing.JPanel loggerPanel;
    private javax.swing.JPanel mainNavigationPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton msgButton;
    private static javax.swing.JTextArea outputArea;
    private javax.swing.JPanel outputPanel;
    private static javax.swing.JTextField pathField;
    private javax.swing.JPanel subNavigationPanel;
    private javax.swing.JPanel userPanel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameView;
    // End of variables declaration//GEN-END:variables
}
