name: Windows Latest x64

on:
  push:
  pull_request:
    branches: 
    - master

jobs:
  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8 for Windows x64
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          architecture: x64
      - name: Build with Ant on Windows x64
        run: ant -noinput -buildfile build.xml
